<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProductSearch($name)
    {
    $rsm = new ResultSetMapping();
    $rsm->addScalarResult('p_id', 'id');
    $rsm->addScalarResult('p_name', 'name');
    $rsm->addScalarResult('p_image', 'image');
    $rsm->addScalarResult('c_id', 'category_id');
    $rsm->addScalarResult('c_name', 'category_name');
    $rsm->addScalarResult('c_icon', 'category_icon'); // Añadido para el icono de la categoría

    $sql = "
        SELECT p.id as p_id, p.name as p_name, p.image as p_image,
               c.id as c_id, c.name as c_name, c.icon as c_icon
        FROM product p
        JOIN category c ON p.category_id = c.id
        WHERE p.name LIKE :name
    ";
    $query = $this->getEntityManager()->createNativeQuery($sql, $rsm);
    $query->setParameter('name', '%' . $name . '%');

    return $query->getResult();
    }
}